### ISSUE TITLE
All the properties are inaccessible

### ISSUE THREAD

**Issue by Jcurrie314** [hadiidbouk/ChartProgressBar-iOS#1]
With the most recent release 1.0.2, I can't set any of the instance variables. The sample also doesn't import ChartProgressBar so I can't imagine how it would have worked

`'data' is inaccessible due to 'internal' protection level`

**Comment by hadiidbouk** [comment]
Thank you @Jcurrie314 for mentioning that, I will appreciate if you send me PR.
or just wait till tomorrow and i will fix it :)

**Comment by hadiidbouk** [comment]
Thank you @Jcurrie314  , Sorry for this stupid problem, you can wait for tomorrow and use the pod or you can clone and use the file in `classes` folder for now.

**Comment by hadiidbouk** [comment]
Fixed here [here](https://github.com/hadiidbouk/ChartProgressBar-iOS/commit/5f1c7d9ab2416a498c5817d2d8bfbc5bd0bc9ffe ) and [here](https://github.com/hadiidbouk/ChartProgressBar-iOS/commit/74b9003a3e56b9b6dd52ccd9a6488835a5d1a608)
